import Foundation

@main enum InteractionTests {
    static func check(_ value: Bool, _ message: String) { precondition(value, message) }
    static func main() {
        let origin = CGPoint(x: 95, y: 60)
        var rub = CompanionGesture(target: .crown, point: origin, time: 0)
        rub.update(point: CGPoint(x: 106, y: 60), time: 0.12, onCrown: true)
        rub.update(point: CGPoint(x: 83, y: 61), time: 0.28, onCrown: true)
        check(rub.phase == .petting && rub.finish() == .pet, "Back-and-forth crown rub should pet")
        rub.update(point: CGPoint(x: 130, y: 60), time: 0.4, onCrown: false)
        check(rub.phase == .petting, "A completed rub must not turn into a window move")

        var jitter = CompanionGesture(target: .crown, point: origin, time: 0)
        jitter.update(point: CGPoint(x: 96, y: 60), time: 0.1, onCrown: true)
        jitter.update(point: origin, time: 0.15, onCrown: true)
        check(jitter.finish() == .poke, "A tap with pointer jitter is a poke, not a rub")
        var move = CompanionGesture(target: .crown, point: origin, time: 0)
        move.update(point: CGPoint(x: 126, y: 60), time: 0.2, onCrown: true)
        move.update(point: origin, time: 0.4, onCrown: true)
        check(move.finish() == .pet, "A long head stroke gives affection instead of moving")
        var leave = CompanionGesture(target: .crown, point: origin, time: 0)
        leave.update(point: CGPoint(x: 95, y: 72), time: 0.2, onCrown: false)
        check(leave.finish() == .pet, "A stroke that leaves the head must still give affection")
        var hold = CompanionGesture(target: .crown, point: origin, time: 0)
        hold.update(point: origin, time: 0.36, onCrown: true)
        check(hold.finish() == .pet, "A brief stationary hold should give affection")

        var body = CompanionGesture(target: .body, point: origin, time: 0)
        check(body.finish() == .openNotes, "Body click opens notes")
        body.update(point: CGPoint(x: 100, y: 60), time: 0.1, onCrown: false)
        check(body.finish() == .moved, "Body drag keeps the small movement threshold")

        var latte = CompanionGesture(target: .latte, point: origin, time: 0)
        check(latte.finish(overCup: true) == .giveLatte, "Cup click still gives a latte")
        check(latte.finish() == .returnLatte, "Click released outside cup must cancel")
        latte.update(point: CGPoint(x: 125, y: 150), time: 0.3, onCrown: false)
        check(latte.phase == .carryingLatte, "Dragged cup must never move the companion")
        check(latte.finish(overCup: true) == .returnLatte, "Cup following pointer alone is not a successful drop")
        check(latte.finish(overHand: true) == .giveLatte, "Dropping in hand feeds her")

        var attitude = AttitudeState()
        check(!attitude.poke(at: 0) && !attitude.poke(at: 0.5) && !attitude.poke(at: 1), "Three pokes should not annoy")
        check(attitude.poke(at: 1.5), "Four rapid pokes earn crossed arms")
        check(!attitude.poke(at: 6), "Separated pokes should not accumulate forever")
        _ = attitude.poke(at: 6.2); _ = attitude.poke(at: 6.4)
        attitude.pet()
        check(!attitude.poke(at: 6.6), "Affection resets the poke streak")
        var care = CompanionCare(timeUntilTumble: 2700)
        check(care.canGiveNotes(needsCoffee: false) && !care.canGiveNotes(needsCoffee: true), "Coffee gates notes")
        check(!care.advanceEligible(by: 2699), "Falls must be rare")
        check(care.advanceEligible(by: 1) && care.upset == .crying, "Eligible time triggers a tumble")
        check(!care.canGiveNotes(needsCoffee: false), "Crying gates notes")
        check(!care.advanceEligible(by: 10000) && care.upset == .crying, "Crying cannot clear on its own")
        care.annoy()
        check(care.upset == .crying, "Annoyance must not replace crying")
        care.soothe()
        check(care.canGiveNotes(needsCoffee: false) && !care.canGiveNotes(needsCoffee: true), "Affection clears upset but not coffee need")
        care.annoy()
        check(!care.canGiveNotes(needsCoffee: false), "Coffee alone cannot clear crossed arms")
        check(care.timeUntilTumble >= 1800 && care.timeUntilTumble <= 3600, "Each tumble resets a long interval")
        var focus = FocusSession()
        focus.start(seconds: 1500)
        check(focus.label == "25:00" && focus.isStretching, "Focus begins with a stretch")
        focus.advance(by: 13)
        check(focus.isStretching, "The full stretch should be visible for fourteen seconds")
        focus.advance(by: 1)
        check(!focus.isStretching && focus.label == "24:46", "She naps after stretching")
        focus.togglePaused()
        focus.advance(by: 1000)
        check(focus.remaining == 1486 && focus.isActive && !focus.isStretching, "Pause freezes the session")
        focus.togglePaused(); focus.advance(by: 166)
        check(focus.isStretching, "She stretches again every three minutes")
        check(focus.advance(by: 1320) && !focus.isActive && focus.phase == .complete, "Focus completes once")
        check(!focus.advance(by: 5), "Completion must not repeat")
        check([0.2, 0.7, 1.3, 1.9, 2.7, 3.3, 3.8].map { FocusSession.wakePoseStep(at: $0) } == Array(0...6), "Waking unfolds through sleepy eyes, sitting, stretching, blinking, and settling")
        check(FocusSession.wakePoseStep(at: 100) == 6, "Waking ends in a settled pose")
        check([0.2, 1.2, 2.2, 3.0, 3.6, 5.8, 7.0, 10.0].map { PerformanceState.breakdancePose(at: $0) } == Array(0...7), "Breakdance includes toprock, footwork, freezes, and backspin in order")
        check(PerformanceState.breakdancePose(at: 12) == 7, "Breakdance ends in its held finish rather than looping back to standing")
        focus.end()
        check(focus.label == "focus" && focus.remaining == 0, "Ending resets focus")
        var adjustableFocus = FocusSession()
        adjustableFocus.start(seconds: 1500); adjustableFocus.advance(by: 11)
        adjustableFocus.adjustRemaining(to: 1800)
        check(adjustableFocus.remaining == 1800 && adjustableFocus.elapsed == 11 && adjustableFocus.phase == .running, "Adjusting running focus preserves time spent and does not pause")
        check(FocusSession.stretchPoseStep(at: adjustableFocus.stretchElapsed) == 6, "Adjusting the timer preserves the current pancake stretch")
        adjustableFocus.togglePaused(); adjustableFocus.adjustRemaining(to: 900)
        check(adjustableFocus.phase == .paused && adjustableFocus.remaining == 900 && adjustableFocus.elapsed == 11, "A paused timer remains paused when adjusted")
        adjustableFocus.adjustRemaining(to: -10)
        check(adjustableFocus.remaining == 60, "Dragging down cannot unexpectedly complete a session")
        adjustableFocus.adjustRemaining(to: .nan)
        check(adjustableFocus.remaining == 60, "Invalid duration changes are ignored")
        var durationDrag = FocusDurationDrag(originalSeconds: 1500)
        check(durationDrag.update(upwardDistance: 2) == nil && !durationDrag.hasDragged, "Pointer jitter stays a click")
        check(durationDrag.update(upwardDistance: 30) == 1800 && durationDrag.hasDragged, "Dragging up adds one minute per six points")
        check(durationDrag.update(upwardDistance: 12) == 1620, "Repeated drag updates stay anchored, not cumulative")
        check(durationDrag.update(upwardDistance: -18) == 1320, "Dragging down subtracts time")
        check(durationDrag.update(upwardDistance: -10000) == 60 && durationDrag.update(upwardDistance: 10000) == 86400, "Duration clamps at one minute and one day")
        check(FocusSession.stretchPoseStep(at: 4) == 2 && FocusSession.stretchPoseStep(at: 11) == 6 && FocusSession.stretchPoseStep(at: 13.5) == 7, "Stretch breaks include splits, low pancake, and recovery")
        var response = CompanionResponse()
        response.acceptLatte(allowed: true)
        response.advance(by: 10, healthy: true, quiet: false, available: false)
        check(response.latteWaiting && response.phase == .idle, "Zoomies wait for sipping and paper gestures to finish")
        response.advance(by: 0.5, healthy: true, quiet: false, available: true)
        check(response.phase == .zoomies && response.zoomiesElapsed == 0.5, "Each latte starts one short burst")
        response.advance(by: 5, healthy: true, quiet: false, available: false)
        check(response.zoomiesElapsed == 0.5, "Dragging, hiding, and pausing freeze zoomies")
        response.advance(by: 7.5, healthy: true, quiet: false, available: true)
        check(response.phase == .idle && !response.latteWaiting, "Zoomies settle after eight eligible seconds without repeating")
        response.acceptLatte(allowed: true)
        response.advance(by: 0.1, healthy: true, quiet: true, available: true)
        check(!response.isActive, "Focus discards queued zoomies")
        response.acceptLatte(allowed: true)
        response.advance(by: 0.1, healthy: false, quiet: false, available: true)
        check(!response.isActive, "An upset robot cannot zoom or bypass care")
        response.acceptLatte(allowed: false)
        check(!response.latteWaiting, "Quiet or reduced-motion latte has no delayed burst")
        response.comfort()
        response.advance(by: 12, healthy: true, quiet: false, available: true)
        check(response.phase == .shySmile && response.reconciliationRemaining == 78, "Reconciliation gives a shy smile after a quiet interval")
        response.advance(by: 2.2, healthy: true, quiet: false, available: true)
        check(response.phase == .reconciliation, "Shy smiles return to quiet company")
        let gentleTime = response.reconciliationRemaining
        response.advance(by: 60, healthy: true, quiet: true, available: true)
        check(response.reconciliationRemaining == gentleTime, "Focus pauses reconciliation without interrupting naps")
        response.advance(by: 90, healthy: true, quiet: false, available: true)
        check(!response.isActive, "Reconciliation ends naturally")
        response.comfort(); response.upset()
        check(!response.isActive, "A new upset clears the old reconciliation")
        let legacyCare = try! JSONDecoder().decode(CompanionCare.self, from: Data(#"{"upset":"crying","timeUntilTumble":5400}"#.utf8))
        check(legacyCare.timeUntilTumble == 3600 && legacyCare.upset == .crying, "Existing tumble time migrates without dismissing crying")
        let restoredCare = try! JSONDecoder().decode(CompanionCare.self, from: JSONEncoder().encode(legacyCare))
        check(restoredCare == legacyCare, "The tumble countdown must only migrate once")
        var performance = PerformanceState(timeUntilRestless: 360)
        check(!performance.advance(by: 359, available: true) && !performance.restless, "Restlessness waits for its eligible deadline")
        let beforeUnavailable = performance.timeUntilRestless
        check(!performance.advance(by: 900, available: false) && performance.timeUntilRestless == beforeUnavailable, "Focus, sleep, care, and pause cannot build restlessness")
        check(!performance.advance(by: .infinity, available: true) && !performance.advance(by: -1, available: true), "Invalid elapsed time cannot trigger a mood")
        check(performance.advance(by: 1, available: true) && performance.restless, "Restless starts once at the deadline")
        check(!performance.advance(by: 900, available: true), "An unresolved need must not repeatedly trigger")
        performance.beginDance()
        check(performance.restless && !performance.awaitingApplause, "Starting or interrupting a dance does not settle restlessness")
        performance.finishDance(chosen: false)
        check(performance.restless && performance.awaitingApplause && performance.applauseEarnsUnlock, "Every incidental dance asks for applause without settling the chosen dance break")
        performance.finishDance(chosen: true)
        check(!performance.restless && !performance.awaitingApplause && performance.timeUntilRestless >= 360 && performance.timeUntilRestless <= 600, "Completing a selected dance settles her without farmable applause")
        performance.finishDance(chosen: false)
        let resetInterval = performance.timeUntilRestless
        check(!performance.advance(by: 1000, available: true) && performance.timeUntilRestless == resetInterval, "Awaiting applause freezes the next restless interval")
        check(performance.applaud() && !performance.applaud() && !performance.awaitingApplause, "One applause resolves one held finish")
        performance.finishDance(chosen: false)
        performance.beginDance()
        check(!performance.awaitingApplause, "A new routine replaces the previous applause request")
        performance.finishDance(chosen: false)
        performance.cancelApplause()
        check(!performance.awaitingApplause && performance.timeUntilRestless == resetInterval, "Focus and care cancel applause without changing the need clock")
        performance.makeRestless()
        performance.finishDance(chosen: true)
        check(!performance.restless && !performance.awaitingApplause, "Chosen dances resolve restlessness without applause")
        check(care.needsAffection && !care.canGiveNotes(needsCoffee: false), "Playful performance state cannot clear the independent care gates")
        performance.finishDance(chosen: false)
        check(performance.applauseRemaining == 6 && performance.applauseFraction == 1 && performance.applauseEarnsUnlock, "A real completed routine starts a six-second clap window")
        performance.advanceApplause(by: 3, available: true)
        check(performance.applauseFraction == 0.5, "The clap fades halfway through its response window")
        performance.advanceApplause(by: 100, available: false)
        check(performance.applauseRemaining == 3, "Hidden, paused and paper-interrupted prompts cannot expire")
        check(!performance.advanceApplause(by: .nan, available: true) && !performance.advanceApplause(by: -1, available: true), "Invalid time cannot expire applause")
        check(performance.advanceApplause(by: 3, available: true) && !performance.applaud(), "At the deadline the prompt expires and late claps fail")
        check(!performance.advanceApplause(by: 3, available: true), "A missed prompt disappoints only once")
        performance.finishDance(chosen: false, earnsUnlock: false)
        check(!performance.applauseEarnsUnlock && performance.applaud(), "Preview applause can show a bow but cannot earn a dance")
        var listening = ListeningState()
        listening.advance(by: 0.6, playing: true, available: true)
        check(!listening.isActive, "Short notification sounds do not trigger headphones")
        listening.advance(by: 0.5, playing: false, available: true)
        listening.advance(by: 0.5, playing: true, available: true)
        check(!listening.isActive, "Separated short sounds do not accumulate")
        listening.advance(by: 0.5, playing: true, available: true)
        check(listening.phase == .puttingOn, "Sustained output starts putting on headphones")
        listening.advance(by: 1.6, playing: true, available: true)
        check(listening.phase == .listening, "The plug-in sequence settles into listening")
        listening.advance(by: 2.5, playing: false, available: true)
        check(listening.phase == .listening, "Track gaps keep the headphones on")
        listening.advance(by: 5, playing: false, available: true, paused: true)
        check(listening.phase == .listening, "Animation pause freezes headphone timing")
        listening.advance(by: 0.5, playing: false, available: true)
        check(listening.phase == .takingOff, "Sustained silence starts taking off headphones")
        listening.advance(by: 0.7, playing: false, available: true)
        check(!listening.isActive, "Headphones are removed after their exit animation")
        listening.advance(by: .nan, playing: true, available: true)
        listening.advance(by: -1, playing: true, available: true)
        check(!listening.isActive, "Invalid elapsed time cannot trigger listening")
        listening.advance(by: 1, playing: true, available: true)
        listening.advance(by: 1, playing: true, available: false)
        check(!listening.isActive, "Focus, care, dancing and hidden windows reset listening")
        print("PASS: sustained playback onset, notification filtering, track-gap grace, headphone animations, pause and interaction priority.")
        var progress = DanceProgress()
        check(progress.unlockedDanceIDs == ["ballet"] && !progress.unlock("house"), "Only Ballet starts unlocked")
        progress.recordClap(); progress.recordClap()
        check(progress.availableUnlocks == 0 && !progress.unlock("house"), "Two timely claps cannot buy a dance")
        progress.recordClap()
        check(progress.availableUnlocks == 1 && progress.unlock("house"), "Three timely claps buy one chosen dance")
        check(progress.availableUnlocks == 0 && !progress.unlock("vogue") && !progress.unlock("house"), "An unlock cannot be spent twice or buy all dances")
        for _ in 0..<3 { progress.recordClap() }
        check(progress.unlock("waacking") && progress.unlockedDanceIDs == ["ballet", "house", "waacking"], "Six claps buy exactly two selected dances")
        check(!progress.unlock("unknown") && !progress.unlock("ballet"), "Unknown or already unlocked dances cannot consume credit")
        let completeProgress = DanceProgress(completedClaps: 100, unlockedDanceIDs: DanceProgress.danceIDs)
        check(completeProgress.availableUnlocks == 0, "A complete repertoire cannot offer empty rewards")
        let progressAgain = try! JSONDecoder().decode(DanceProgress.self, from: JSONEncoder().encode(progress))
        check(progressAgain == progress, "Earned claps and chosen routines round-trip")
        let invalidProgress = try! JSONDecoder().decode(DanceProgress.self, from: Data(#"{"completedClaps":-5,"unlockedDanceIDs":["unknown","house","house"]}"#.utf8))
        check(invalidProgress.completedClaps == 0 && invalidProgress.unlockedDanceIDs == ["ballet", "house"], "Decoded progress is clamped, deduplicated and preserves Ballet")

        var wallet = DanceProgress(completedClaps: 4)
        check(wallet.unlock("house") && wallet.clapBalance == 1, "Unlock costs exactly three claps")
        check(wallet.payForReplay("house") && wallet.clapBalance == 0, "Replaying spends one clap")
        check(!wallet.payForReplay("house") && !wallet.unlock("vogue"), "Spent replay credits cannot also fund unlocks")
        check(!wallet.payForReplay("unknown"), "Unknown routines cannot spend claps")
        let savedWallet = try! JSONDecoder().decode(DanceProgress.self, from: JSONEncoder().encode(wallet))
        check(savedWallet == wallet && savedWallet.clapBalance == 0, "Replay spending survives restarting")
        let legacyWallet = try! JSONDecoder().decode(DanceProgress.self, from: Data(#"{"completedClaps":7,"unlockedDanceIDs":["ballet","house"]}"#.utf8))
        check(legacyWallet.clapBalance == 4 && legacyWallet.replayClapsSpent == 0, "Existing lifetime claps and unlock spending migrate intact")
        performance.finishDance(chosen: true, earnsUnlock: false)
        check(!performance.awaitingApplause, "Menu dances never offer a farmable clap")

        var stimulation = StimulationState()
        for i in 0..<5 { check(!stimulation.interact(at: Double(i)), "A little attention should stay welcome") }
        check(stimulation.interact(at: 5) && stimulation.overstimulated, "Six interactions in twenty seconds ask for quiet")
        stimulation.advance(by: 29, available: true)
        check(stimulation.overstimulated && stimulation.quietRemaining == 1, "She needs the full quiet interval")
        stimulation.advance(by: 1000, available: false)
        check(stimulation.quietRemaining == 1, "Hidden or paused time cannot consume recovery")
        stimulation.interact(at: 10)
        check(stimulation.quietRemaining == 1, "Ignored attention does not restart her quiet time")
        stimulation.makeOverstimulated()
        check(stimulation.quietRemaining == 1, "An existing overwhelmed episode cannot restart recovery")
        check(stimulation.advance(by: 30, available: true) && !stimulation.overstimulated, "Quiet company resolves overstimulation")
        for i in 0..<10 { stimulation.interact(at: 20 + Double(i)) }
        check(!stimulation.overstimulated && stimulation.cooldownRemaining == 60, "A cooldown prevents immediate retriggering")
        stimulation.advance(by: 60, available: true)
        for i in 0..<10 { stimulation.interact(at: 100 + Double(i) * 21) }
        check(!stimulation.overstimulated, "Attention spaced beyond twenty seconds does not accumulate forever")
        stimulation.makeOverstimulated()
        stimulation.advance(by: .infinity, available: true)
        check(stimulation.overstimulated, "Invalid time cannot resolve a need")
        print("PASS: overstimulation threshold, quiet recovery, repeated attention, cooldown, pause guards, and spaced interactions.")
        print("PASS: restless eligible timing, pause guards, completed versus interrupted dance, applause, reset intervals, and independent care needs.")
        print("PASS: head stroke/hold versus body drag, latte drops, poke timing, independent note gates, persistent crying, rare tumble intervals, focus stretching/napping/pause/completion.")
        print("PASS: latte response timing, busy/hidden/pause guards, focus/upset cancellation, quiet reconciliation, shy smiles, and natural expiry.")
    }
}
