import Foundation

@main enum StoreTests {
    static func main() throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("velvet-test-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: directory) }
        let store = NoteStore(directory: directory)
        let first = store.create()
        store.update(first, title: "First thought ✨", body: "Coffee\nCrème brûlée & a fabulous idea 👢")
        let second = store.create()
        store.update(second, title: "A second thought", body: "Never lose this")
        store.pin(first)
        precondition(store.sortedNotes.first?.id == first, "Pinned notes should come first")
        store.query = "BRÛLÉE"
        precondition(store.sortedNotes.count == 1, "Search should find Unicode content case-insensitively")
        store.query = ""
        store.trash(first)
        precondition(store.activeCount == 1 && store.trashCount == 1, "Trash should preserve deleted notes")
        store.showingTrash = true
        precondition(store.sortedNotes.first?.id == first)
        store.restore(first)
        precondition(store.activeCount == 2 && store.trashCount == 0)
        store.setPreferences { $0.x = -1600; $0.y = 80; $0.shortcut = 1; $0.paused = true }
        var danceProgress = DanceProgress()
        for _ in 0..<3 { danceProgress.recordClap() }
        precondition(danceProgress.unlock("house"))
        store.setDanceProgress(danceProgress)
        precondition(store.flush(), "Saving should succeed")
        let reopened = NoteStore(directory: directory)
        precondition(reopened.archive.notes.count == 2, "Notes should survive a restart")
        precondition(reopened.danceProgress == danceProgress, "Three claps and the chosen dance must survive a restart")
        precondition(reopened.archive.notes.first(where: { $0.id == first })?.body == "Coffee\nCrème brûlée & a fabulous idea 👢")
        precondition(reopened.preferences.x == -1600 && reopened.preferences.shortcut == 1 && reopened.preferences.paused)
        precondition(reopened.markdown(reopened.archive.notes.first(where: { $0.id == first })!).contains("# First thought ✨\n\nCoffee"))
        reopened.trash(second)
        precondition(reopened.flush())
        let withTrash = NoteStore(directory: directory)
        precondition(withTrash.trashCount == 1, "Trash should survive a restart")
        let file = directory.appendingPathComponent("notes.json")
        // Older notes files have no coffee state. They must still open intact.
        var legacy = try JSONSerialization.jsonObject(with: Data(contentsOf: file)) as! [String: Any]
        legacy.removeValue(forKey: "coffee")
        legacy.removeValue(forKey: "care")
        legacy.removeValue(forKey: "danceProgress")
        try JSONSerialization.data(withJSONObject: legacy).write(to: file)
        let migrated = NoteStore(directory: directory)
        precondition(migrated.archive.notes.count == 2 && migrated.saveError == nil)
        precondition(!migrated.coffee.needsCoffee)
        precondition(!migrated.care.needsAffection)
        precondition(migrated.danceProgress == DanceProgress(), "Existing archives without unlocks start with Ballet while preserving notes")
        var wellbeing = CompanionCare(timeUntilTumble: 3200)
        wellbeing.annoy(); migrated.setCare(wellbeing)
        precondition(migrated.flush())
        precondition(NoteStore(directory: directory).care.upset == .annoyed, "Crossed arms must survive a restart")
        wellbeing.tumble(); migrated.setCare(wellbeing)
        precondition(migrated.flush())
        precondition(NoteStore(directory: directory).care.upset == .crying, "Restarting must not bypass crying")
        wellbeing.soothe(); migrated.setCare(wellbeing)
        var care = migrated.coffee
        care.advance(by: CoffeeState.patience - 0.5)
        precondition(!care.needsCoffee, "Coffee should not be needed before the deadline")
        care.advance(by: 0.5)
        precondition(care.needsCoffee, "Reaching the deadline should make her grumpy")
        care.advance(by: .infinity)
        care.advance(by: -100)
        precondition(care.awakeSeconds == CoffeeState.patience)
        migrated.setCoffee(care)
        precondition(migrated.flush())
        let stillGrumpy = NoteStore(directory: directory)
        precondition(stillGrumpy.coffee.needsCoffee, "Restarting should not bypass the coffee mechanic")
        care.giveCoffee()
        precondition(!care.needsCoffee && care.awakeSeconds == 0 && care.coffeesGiven == 1)
        migrated.setCoffee(care)
        precondition(migrated.flush())
        let caffeinated = NoteStore(directory: directory)
        precondition(!caffeinated.coffee.needsCoffee && caffeinated.coffee.coffeesGiven == 1)
        let damaged = Data("not valid JSON; keep this for recovery".utf8)
        try damaged.write(to: file)
        let unreadable = NoteStore(directory: directory)
        precondition(unreadable.saveError != nil)
        unreadable.create()
        precondition(!unreadable.flush(), "A corrupt archive must not be silently overwritten")
        let retained = try Data(contentsOf: file)
        precondition(retained == damaged, "Original data should be retained")
        print("PASS: notes persistence, Unicode, trash/restore, export, legacy migration, coffee deadline, coffee recovery, persistent grumpiness, corrupt-file preservation")
    }
}
